# Configuration AlertManager pour la gestion des alertes
global:
  smtp_smarthost: 'sandbox.smtp.mailtrap.io:2525'  # Mailtrap SMTP server
  smtp_from: 'alertmanager@monitoring.local'
  smtp_auth_username: '3f5687df1ffed9'              # Mailtrap username
  smtp_auth_password: '5a5e3275b9056e'              # Mailtrap password

# Configuration du routage des alertes
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Alertes CPU spécifiques - notification immédiate à l'utilisateur
    - match:
        alert_type: cpu_high
      receiver: 'cpu-alerts-user'
      group_wait: 0s
      repeat_interval: 5m

    # Alertes critiques - notification immédiate
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Alertes warning - notification groupée
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

# Configuration des récepteurs d'alertes
receivers:
  # Webhook par défaut
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Alertes CPU spécifiques pour l'utilisateur
  - name: 'cpu-alerts-user'
    email_configs:
      - to: 'oussamabartil.04@gmail.com'
        html: 'Alerte CPU détectée sur le système (seuil: 30%). Détails: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  # Alertes critiques - Email
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@company.com'
        html: 'Une alerte critique a été détectée. Détails: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  # Alertes warning - Email seulement
  - name: 'warning-alerts'
    email_configs:
      - to: 'team@company.com'
        html: 'Une alerte warning a été détectée. Détails: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

# Configuration de l'inhibition (suppression d'alertes redondantes)
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
