# Test rapide du seuil CPU 30%
Write-Output "🎯 CONFIGURATION MISE À JOUR - SEUIL CPU 30%"
Write-Output "============================================"
Write-Output ""
Write-Output "✅ Modifications appliquées:"
Write-Output "- Seuil CPU: 30% (au lieu de 85%)"
Write-Output "- Durée: 2 minutes (au lieu de 5 minutes)"
Write-Output "- Email: oussamabartil.04@gmail.com"
Write-Output ""
Write-Output "🔄 Redémarrage de Prometheus en cours..."
docker restart prometheus
Write-Output "✅ Prometheus redémarré"
Write-Output ""
Write-Output "📊 État des services:"
docker ps --format "table {{.Names}}\t{{.Status}}"
Write-Output ""
Write-Output "🌐 Interfaces à surveiller:"
Write-Output "- Prometheus Alerts: http://localhost:9090/alerts"
Write-Output "- AlertManager: http://localhost:9093"
Write-Output ""
Write-Output "⚡ Avec le seuil de 30%, l'alerte devrait se déclencher"
Write-Output "   plus facilement lors d'une utilisation normale!"
